site_name: Theophysics Research Platform
site_description: Curated highlights from the Theophysics research archive
site_author: David Lowe
site_url: https://theophysics.pages.dev
theme:
  name: material
  palette:
  - scheme: slate
    primary: black
    accent: cyan
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.top
  - search.highlight
  - search.share
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- toc
- tables
plugins:
- search
nav:
- Home: index.md
